name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: cells.gatunes.com
          exclude_assets: '.github'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ''
